---
abstract: "Syntactic sugar for a script's main routine"
author:
  - 'Stephen Nelson <stephenenelson@mac.com>'
build_requires:
  FindBin: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-Main
requires:
  Sub::Exporter: 0.985
  strict: 0
  warnings: 0
version: 0.002
